const SERVICES = [
  { title: 'EC2' },
  { title: 'Lightsail' },
  { title: 'Lambda' },
  { title: 'Batch' },
  { title: 'Elastic Beanstalk' },
  { title: 'Serverless Application Repository' },
  { title: 'AWS Outposts' },
  { title: 'EC2 Image Builder' },
  { title: 'S3' },
  { title: 'EFS' },
  { title: 'FSx' },
  { title: 'S3 Glacier' },
  { title: 'Storage Gateway' },
  { title: 'AWS Backup' },
  { title: 'RDS' },
  { title: 'DynamoDB' },
  { title: 'ElastiCache' },
  { title: 'Neptune' },
  { title: 'Amazon Redshift' },
  { title: 'Amazon QLDB' },
  { title: 'Amazon DocumentDB' },
  { title: 'Managed Cassandra Service' },
  { title: 'AWS Migration Hub' },
  { title: 'Application Discovery Service' },
  { title: 'Database Migration Service' },
  { title: 'Server Migration Service' },
  { title: 'AWS Transfer Family' },
  { title: 'Snowball' },
  { title: 'DataSync' },
  { title: 'VPC' },
  { title: 'CloudFront' },
  { title: 'Route 53' },
  { title: 'API Gateway' },
  { title: 'Direct Connect' },
  { title: 'AWS App Mesh' },
  { title: 'AWS Cloud Map' },
  { title: 'Global Accelerator' },
  { title: 'CodeStar' },
  { title: 'CodeCommit' },
  { title: 'CodeBuild' },
  { title: 'CodeDeploy' },
  { title: 'CodePipeline' },
  { title: 'Cloud9' },
  { title: 'X-Ray' },
  { title: 'AWS RoboMaker' },
  { title: 'AWS IQ' },
  { title: 'Support' },
  { title: 'Managed Services' },
  { title: 'Amazon Managed Blockchain' },
  { title: 'Ground Station' },
  { title: 'Amazon Braket' },
  { title: 'AWS Organizations' },
  { title: 'CloudWatch' },
  { title: 'AWS Auto Scaling' },
  { title: 'CloudFormation' },
  { title: 'CloudTrail' },
  { title: 'Config' },
  { title: 'OpsWorks' },
  { title: 'Service Catalog' },
  { title: 'Systems Manager' },
  { title: 'AWS AppConfig' },
  { title: 'Trusted Advisor' },
  { title: 'Control Tower' },
  { title: 'AWS License Manager' },
  { title: 'AWS Well-Architected Tool' },
  { title: 'Personal Health Dashboard' },
  { title: 'AWS Chatbot' },
  { title: 'Launch Wizard' },
  { title: 'AWS Compute Optimizer' },
  { title: 'Elastic Transcoder' },
  { title: 'Kinesis Video Streams' },
  { title: 'MediaConnect' },
  { title: 'MediaConvert' },
  { title: 'MediaLive' },
  { title: 'MediaPackage' },
  { title: 'MediaStore' },
  { title: 'MediaTailor' },
  { title: 'Elemental Appliances & Software' },
  { title: 'Amazon SageMaker' },
  { title: 'Amazon CodeGuru' },
  { title: 'Amazon Comprehend' },
  { title: 'Amazon Forecast' },
  { title: 'Amazon Fraud Detector' },
  { title: 'Amazon Kendra' },
  { title: 'Amazon Lex' },
  { title: 'Amazon Machine Learning' },
  { title: 'Amazon Personalize' },
  { title: 'Amazon Polly' },
  { title: 'Amazon Rekognition' },
  { title: 'Amazon Textract' },
  { title: 'Amazon Transcribe' },
  { title: 'Amazon Translate' },
  { title: 'AWS DeepLens' },
  { title: 'AWS DeepRacer' },
  { title: 'Amazon Augmented AI' },
  { title: 'AWS DeepComposer' },
  { title: 'Athena' },
  { title: 'EMR' },
  { title: 'CloudSearch' },
  { title: 'Elasticsearch Service' },
  { title: 'Kinesis' },
  { title: 'QuickSight' },
  { title: 'Data Pipeline' },
  { title: 'AWS Data Exchange' },
  { title: 'AWS Glue' },
  { title: 'AWS Lake Formation' },
  { title: 'MSK' },
  { title: 'IAM' },
  { title: 'Resource Access Manager' },
  { title: 'Cognito' },
  { title: 'Secrets Manager' },
  { title: 'GuardDuty' },
  { title: 'Inspector' },
  { title: 'Amazon Macie' },
  { title: 'AWS Single Sign-On' },
  { title: 'Certificate Manager' },
  { title: 'Key Management Service' },
  { title: 'CloudHSM' },
  { title: 'Directory Service' },
  { title: 'WAF & Shield' },
  { title: 'AWS Firewall Manager' },
  { title: 'Artifact' },
  { title: 'Security Hub' },
  { title: 'Detective' },
  { title: 'AWS Amplify' },
  { title: 'Mobile Hub' },
  { title: 'AWS AppSync' },
  { title: 'Device Farm' },
  { title: 'Amazon Sumerian' },
  { title: 'Step Functions' },
  { title: 'Amazon EventBridge' },
  { title: 'Amazon MQ' },
  { title: 'Simple Notification Service' },
  { title: 'Simple Queue Service' },
  { title: 'SWF' },
  { title: 'AWS Cost Explorer' },
  { title: 'AWS Budgets' },
  { title: 'AWS Marketplace Subscriptions' },
  { title: 'Amazon Connect' },
  { title: 'Pinpoint' },
  { title: 'Simple Email Service' },
  { title: 'Alexa for Business' },
  { title: 'Amazon Chime' },
  { title: 'WorkMail' },
  { title: 'WorkSpaces' },
  { title: 'AppStream 2.0' },
  { title: 'WorkDocs' },
  { title: 'WorkLink' },
  { title: 'IoT Core' },
  { title: 'FreeRTOS' },
  { title: 'IoT 1-Click' },
  { title: 'IoT Analytics' },
  { title: 'IoT Device Defender' },
  { title: 'IoT Device Management' },
  { title: 'IoT Events' },
  { title: 'IoT Greengrass' },
  { title: 'IoT SiteWise' },
  { title: 'IoT Things Graph' },
  { title: 'Amazon GameLift' },
  { title: 'Elastic Container Registry' },
  { title: 'Elastic Container Service' },
  { title: 'Elastic Kubernetes Service' },
];

export default SERVICES;
